apiVersion: extensions/v1beta1
kind: Deployment
metadata:  
  labels:
    app: todo-web-application-h2    
  name: todo-web-application-h2
  namespace: default
spec:  
  replicas: 2
  minReadySeconds: 45  
  selector:
    matchLabels:
      app: todo-web-application-h2            
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:      
      labels:
        app: todo-web-application-h2        
    spec:
      containers:
      - image: alvieira/todo-web-application-h2:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: todo-web-application-h2      
      restartPolicy: Always      
      terminationGracePeriodSeconds: 30
---      
apiVersion: v1
kind: Service
metadata:  
  labels:
    app: todo-web-application-h2
  name: todo-web-application-h2
  namespace: default  
spec:
  clusterIP: 10.48.1.42  
  ports:
  - nodePort: 32446
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: todo-web-application-h2
  sessionAffinity: ClientIP
  type: LoadBalancer
